language: node_js
node_js: node
os:
  - linux
  - windows
  - osx
before_script:
  - npm install
script:
  - test/sass.sh
  - test/scss.sh
  - test/less.sh
  - test/stylus.sh
branches:
  only:
  - master
