on:
  push:
  pull_request:
    branches: [main]
jobs:
  test-sytax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run-script sass
      - run: npm run-script scss
      - run: npm run-script less
      - run: npm run-script styl
  size-limits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm install
      - run: npm run-script prefix
      - run: npm run-script minify
      - run: npm run-script compress
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

