# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build SASS
        run: /test/sass.sh
      - name: Build SCSS
        run: /test/scss.sh
      - name: Build LESS
        run: /test/less.sh
      - name: Build STYLUS
        run: /test/stylus.sh        
